/*
 * Selling Partner API for Replenishment
 * The Selling Partner API for Replenishment (Replenishment API) provides programmatic access to replenishment program metrics and offers. These programs provide recurring delivery (automatic or manual) of any replenishable item at a frequency chosen by the customer.
 *
 * OpenAPI spec version: 2022-11-07
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.amazon.spapi.model.replenishment_api_model;

import java.util.Objects;
import java.util.Arrays;
import com.amazon.spapi.model.replenishment_api_model.ListOfferMetricsSortKey;
import com.amazon.spapi.model.replenishment_api_model.SortOrder;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Use these parameters to sort the response.
 */
@ApiModel(description = "Use these parameters to sort the response.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-11-30T16:52:44.904+08:00")
public class ListOfferMetricsRequestSort {
  @SerializedName("order")
  private SortOrder order = null;

  @SerializedName("key")
  private ListOfferMetricsSortKey key = null;

  public ListOfferMetricsRequestSort order(SortOrder order) {
    this.order = order;
    return this;
  }

   /**
   * The sort order.
   * @return order
  **/
  @ApiModelProperty(required = true, value = "The sort order.")
  public SortOrder getOrder() {
    return order;
  }

  public void setOrder(SortOrder order) {
    this.order = order;
  }

  public ListOfferMetricsRequestSort key(ListOfferMetricsSortKey key) {
    this.key = key;
    return this;
  }

   /**
   * Get key
   * @return key
  **/
  @ApiModelProperty(required = true, value = "")
  public ListOfferMetricsSortKey getKey() {
    return key;
  }

  public void setKey(ListOfferMetricsSortKey key) {
    this.key = key;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListOfferMetricsRequestSort listOfferMetricsRequestSort = (ListOfferMetricsRequestSort) o;
    return Objects.equals(this.order, listOfferMetricsRequestSort.order) &&
        Objects.equals(this.key, listOfferMetricsRequestSort.key);
  }

  @Override
  public int hashCode() {
    return Objects.hash(order, key);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListOfferMetricsRequestSort {\n");
    
    sb.append("    order: ").append(toIndentedString(order)).append("\n");
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

