/*
 * Selling Partner API for Replenishment
 * The Selling Partner API for Replenishment (Replenishment API) provides programmatic access to replenishment program metrics and offers. These programs provide recurring delivery (automatic or manual) of any replenishable item at a frequency chosen by the customer.
 *
 * OpenAPI spec version: 2022-11-07
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.amazon.spapi.model.replenishment_api_model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * The metric name and description.
 */
@JsonAdapter(Metric.Adapter.class)
public enum Metric {
  
  SHIPPED_SUBSCRIPTION_UNITS("SHIPPED_SUBSCRIPTION_UNITS"),
  
  TOTAL_SUBSCRIPTIONS_REVENUE("TOTAL_SUBSCRIPTIONS_REVENUE"),
  
  ACTIVE_SUBSCRIPTIONS("ACTIVE_SUBSCRIPTIONS"),
  
  NOT_DELIVERED_DUE_TO_OOS("NOT_DELIVERED_DUE_TO_OOS"),
  
  SUBSCRIBER_NON_SUBSCRIBER_AVERAGE_REVENUE("SUBSCRIBER_NON_SUBSCRIBER_AVERAGE_REVENUE");

  private String value;

  Metric(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static Metric fromValue(String text) {
    for (Metric b : Metric.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<Metric> {
    @Override
    public void write(final JsonWriter jsonWriter, final Metric enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public Metric read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return Metric.fromValue(String.valueOf(value));
    }
  }
}

