/*
 * Selling Partner API for Replenishment
 * The Selling Partner API for Replenishment (Replenishment API) provides programmatic access to replenishment program metrics and offers. These programs provide recurring delivery (automatic or manual) of any replenishable item at a frequency chosen by the customer.
 *
 * OpenAPI spec version: 2022-11-07
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.amazon.spapi.model.replenishment_api_model;

import java.util.Objects;
import java.util.Arrays;
import com.amazon.spapi.model.replenishment_api_model.AutoEnrollmentPreference;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * An object which contains the preferences applied to the offer.
 */
@ApiModel(description = "An object which contains the preferences applied to the offer.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-11-30T16:52:44.904+08:00")
public class OfferProgramConfigurationPreferences {
  @SerializedName("autoEnrollment")
  private AutoEnrollmentPreference autoEnrollment = null;

  public OfferProgramConfigurationPreferences autoEnrollment(AutoEnrollmentPreference autoEnrollment) {
    this.autoEnrollment = autoEnrollment;
    return this;
  }

   /**
   * The auto-enrollment preference indicates whether the offer is opted-in to or opted-out of Amazon&#39;s auto-enrollment feature.
   * @return autoEnrollment
  **/
  @ApiModelProperty(value = "The auto-enrollment preference indicates whether the offer is opted-in to or opted-out of Amazon's auto-enrollment feature.")
  public AutoEnrollmentPreference getAutoEnrollment() {
    return autoEnrollment;
  }

  public void setAutoEnrollment(AutoEnrollmentPreference autoEnrollment) {
    this.autoEnrollment = autoEnrollment;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OfferProgramConfigurationPreferences offerProgramConfigurationPreferences = (OfferProgramConfigurationPreferences) o;
    return Objects.equals(this.autoEnrollment, offerProgramConfigurationPreferences.autoEnrollment);
  }

  @Override
  public int hashCode() {
    return Objects.hash(autoEnrollment);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OfferProgramConfigurationPreferences {\n");
    
    sb.append("    autoEnrollment: ").append(toIndentedString(autoEnrollment)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

