/*
 * Selling Partner API for Supply Sources
 * Manage configurations and capabilities of seller supply sources.
 *
 * OpenAPI spec version: 2020-07-01
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.amazon.spapi.model.supply_sources_api_model;

import java.util.Objects;
import java.util.Arrays;
import com.amazon.spapi.model.supply_sources_api_model.SupplySourceList;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * The paginated list of supply sources.
 */
@ApiModel(description = "The paginated list of supply sources.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-11-29T10:47:24.793+08:00")
public class GetSupplySourcesResponse {
  @SerializedName("supplySources")
  private SupplySourceList supplySources = null;

  @SerializedName("nextPageToken")
  private String nextPageToken = null;

  public GetSupplySourcesResponse supplySources(SupplySourceList supplySources) {
    this.supplySources = supplySources;
    return this;
  }

   /**
   * Get supplySources
   * @return supplySources
  **/
  @ApiModelProperty(value = "")
  public SupplySourceList getSupplySources() {
    return supplySources;
  }

  public void setSupplySources(SupplySourceList supplySources) {
    this.supplySources = supplySources;
  }

  public GetSupplySourcesResponse nextPageToken(String nextPageToken) {
    this.nextPageToken = nextPageToken;
    return this;
  }

   /**
   * If present, use this pagination token to retrieve the next page of supply sources.
   * @return nextPageToken
  **/
  @ApiModelProperty(value = "If present, use this pagination token to retrieve the next page of supply sources.")
  public String getNextPageToken() {
    return nextPageToken;
  }

  public void setNextPageToken(String nextPageToken) {
    this.nextPageToken = nextPageToken;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetSupplySourcesResponse getSupplySourcesResponse = (GetSupplySourcesResponse) o;
    return Objects.equals(this.supplySources, getSupplySourcesResponse.supplySources) &&
        Objects.equals(this.nextPageToken, getSupplySourcesResponse.nextPageToken);
  }

  @Override
  public int hashCode() {
    return Objects.hash(supplySources, nextPageToken);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetSupplySourcesResponse {\n");
    
    sb.append("    supplySources: ").append(toIndentedString(supplySources)).append("\n");
    sb.append("    nextPageToken: ").append(toIndentedString(nextPageToken)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

