/*
 * Selling Partner API for Supply Sources
 * Manage configurations and capabilities of seller supply sources.
 *
 * OpenAPI spec version: 2020-07-01
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.amazon.spapi.model.supply_sources_api_model;

import java.util.Objects;
import java.util.Arrays;
import com.amazon.spapi.model.supply_sources_api_model.ThroughputCap;
import com.amazon.spapi.model.supply_sources_api_model.ThroughputUnit;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * The throughput configuration.
 */
@ApiModel(description = "The throughput configuration.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-11-29T16:11:50.997+08:00")
public class ThroughputConfig {
  @SerializedName("throughputCap")
  private ThroughputCap throughputCap = null;

  @SerializedName("throughputUnit")
  private ThroughputUnit throughputUnit = null;

  public ThroughputConfig throughputCap(ThroughputCap throughputCap) {
    this.throughputCap = throughputCap;
    return this;
  }

   /**
   * Get throughputCap
   * @return throughputCap
  **/
  @ApiModelProperty(value = "")
  public ThroughputCap getThroughputCap() {
    return throughputCap;
  }

  public void setThroughputCap(ThroughputCap throughputCap) {
    this.throughputCap = throughputCap;
  }

  public ThroughputConfig throughputUnit(ThroughputUnit throughputUnit) {
    this.throughputUnit = throughputUnit;
    return this;
  }

   /**
   * Get throughputUnit
   * @return throughputUnit
  **/
  @ApiModelProperty(required = true, value = "")
  public ThroughputUnit getThroughputUnit() {
    return throughputUnit;
  }

  public void setThroughputUnit(ThroughputUnit throughputUnit) {
    this.throughputUnit = throughputUnit;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ThroughputConfig throughputConfig = (ThroughputConfig) o;
    return Objects.equals(this.throughputCap, throughputConfig.throughputCap) &&
        Objects.equals(this.throughputUnit, throughputConfig.throughputUnit);
  }

  @Override
  public int hashCode() {
    return Objects.hash(throughputCap, throughputUnit);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ThroughputConfig {\n");
    
    sb.append("    throughputCap: ").append(toIndentedString(throughputCap)).append("\n");
    sb.append("    throughputUnit: ").append(toIndentedString(throughputUnit)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

