/*
 * Selling Partner API for Supply Sources
 * Manage configurations and capabilities of seller supply sources.
 *
 * OpenAPI spec version: 2020-07-01
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.amazon.spapi.model.supply_sources_api_model;

import java.util.Objects;
import java.util.Arrays;
import com.amazon.spapi.model.supply_sources_api_model.SupplySourceCapabilities;
import com.amazon.spapi.model.supply_sources_api_model.SupplySourceConfiguration;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * A request to update the configuration and capabilities of a supply source.
 */
@ApiModel(description = "A request to update the configuration and capabilities of a supply source.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-11-29T16:11:50.997+08:00")
public class UpdateSupplySourceRequest {
  @SerializedName("alias")
  private String alias = null;

  @SerializedName("configuration")
  private SupplySourceConfiguration _configuration = null;

  @SerializedName("capabilities")
  private SupplySourceCapabilities capabilities = null;

  public UpdateSupplySourceRequest alias(String alias) {
    this.alias = alias;
    return this;
  }

   /**
   * Get alias
   * @return alias
  **/
  @ApiModelProperty(value = "")
  public String getAlias() {
    return alias;
  }

  public void setAlias(String alias) {
    this.alias = alias;
  }

  public UpdateSupplySourceRequest _configuration(SupplySourceConfiguration _configuration) {
    this._configuration = _configuration;
    return this;
  }

   /**
   * Get _configuration
   * @return _configuration
  **/
  @ApiModelProperty(value = "")
  public SupplySourceConfiguration getConfiguration() {
    return _configuration;
  }

  public void setConfiguration(SupplySourceConfiguration _configuration) {
    this._configuration = _configuration;
  }

  public UpdateSupplySourceRequest capabilities(SupplySourceCapabilities capabilities) {
    this.capabilities = capabilities;
    return this;
  }

   /**
   * Get capabilities
   * @return capabilities
  **/
  @ApiModelProperty(value = "")
  public SupplySourceCapabilities getCapabilities() {
    return capabilities;
  }

  public void setCapabilities(SupplySourceCapabilities capabilities) {
    this.capabilities = capabilities;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateSupplySourceRequest updateSupplySourceRequest = (UpdateSupplySourceRequest) o;
    return Objects.equals(this.alias, updateSupplySourceRequest.alias) &&
        Objects.equals(this._configuration, updateSupplySourceRequest._configuration) &&
        Objects.equals(this.capabilities, updateSupplySourceRequest.capabilities);
  }

  @Override
  public int hashCode() {
    return Objects.hash(alias, _configuration, capabilities);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateSupplySourceRequest {\n");
    
    sb.append("    alias: ").append(toIndentedString(alias)).append("\n");
    sb.append("    _configuration: ").append(toIndentedString(_configuration)).append("\n");
    sb.append("    capabilities: ").append(toIndentedString(capabilities)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

